# Generated by Django 5.2.4 on 2025-08-04 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmarks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PickTheme',
            fields=[
                ('picktheme_id', models.AutoField(primary_key=True, serialize=False)),
                ('theme', models.CharField(choices=[('Light Mode', 'light'), ('Dark Mode', 'dark')], max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user',), name='One Entry Per User')],
            },
        ),
    ]
